force-app/main/sacTree/objects/DynamicPicklist__mdt/DynamicPicklist__mdt.object-meta.xml
<CustomObject>
    <label>Dynamic Picklist</label>
    <pluralLabel>Dynamic Picklists</pluralLabel>
</CustomObject>

force-app/main/sacTree/objects/DynamicPicklist__mdt/fields/sObject__c.field-meta.xml
<CustomField>
    <fullName>sObject__c</fullName>
    <inlineHelpText>sObject API Name (custom or standard)</inlineHelpText>
    <label>sObject</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/sacTree/objects/DynamicPicklistLevel__mdt/DynamicPicklistLevel__mdt.object-meta.xml
<CustomObject>
    <label>Dynamic Picklist Level</label>
    <pluralLabel>Dynamic Picklist Levels</pluralLabel>
</CustomObject>

force-app/main/sacTree/objects/DynamicPicklistLevel__mdt/fields/DynamicPicklistSObject__c.field-meta.xml
<CustomField>
    <fullName>DynamicPicklistSObject__c</fullName>
    <label>Dynamic Picklist sObject</label>
    <referenceTo>DynamicPicklist__mdt</referenceTo>
    <relationshipLabel>Dynamic Picklist Levels</relationshipLabel>
    <relationshipName>DynamicPicklistLevels</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/sacTree/objects/DynamicPicklistLevel__mdt/fields/FieldMapping__c.field-meta.xml
<CustomField>
    <fullName>FieldMapping__c</fullName>
    <label>Field Mapping</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/sacTree/objects/DynamicPicklistLevel__mdt/fields/LevelOrder__c.field-meta.xml
<CustomField>
    <fullName>LevelOrder__c</fullName>
    <label>Level Order</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/sacTree/classes/DynamicPicklistSelector.cls
public with sharing class DynamicPicklistSelector {
  public static List<DynamicPicklist__mdt> findByNameWithLevels(String name) {
    return [
      SELECT
        Id,
        DeveloperName,
        sObject__c,
        (
          SELECT Id, MasterLabel, DeveloperName, LevelOrder__c, FieldMapping__c
          FROM DynamicPicklistLevels__r
          ORDER BY LevelOrder__c ASC
        )
      FROM DynamicPicklist__mdt
      WHERE DeveloperName = :name
      LIMIT 1
    ];
  }
}