force-app/main/sacTree/objects/SACTree__c/SACTree__c.object-meta.xml
<CustomObject>
    <label>SAC Tree</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAC Trees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/sacTree/objects/SACTree__c/fields/ParentLevel__c.field-meta.xml
<CustomField>
    <fullName>ParentLevel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Level</label>
    <referenceTo>SACTree__c</referenceTo>
    <relationshipLabel>Child Level</relationshipLabel>
    <relationshipName>ChildLevel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/sacTree/classes/SacTreeSelector.cls
public with sharing class SacTreeSelector {

    public static List<SacTree__c> getTreeOptionListByLevel(String level) {
        return [SELECT Id, Name FROM SacTree__c WHERE RecordType.Name = :level WITH SECURITY_ENFORCED LIMIT 10000];
    }

    public static List<SacTree__c> getTreeOptionListByParentId(Id levelParentId) {
        return [SELECT Id, Name FROM SacTree__c WHERE ParentLevel__c = :levelParentId WITH SECURITY_ENFORCED LIMIT 10000];
    }
}